server:
  port: 0

spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value-deserializer: ru.practicum.aggregator.serialization.UserActionAvroDeserializer
      enable-auto-commit: false
      properties:
        specific.avro.reader: true
        session.timeout.ms: 60000
        request.timeout.ms: 60000
        max.poll.interval.ms: 600000
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: ru.practicum.aggregator.serialization.EventSimilarityAvroSerializer
      properties:
        request.timeout.ms: 60000
        delivery.timeout.ms: 120000
    listener:
      ack-mode: manual
      poll-timeout: 5000
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN